const days = [
 {n:1,title:'建立阅读系统',tag:'过去时基础 · 社会',goal:'先抓主旨，再看细节；建立 passé composé、imparfait、plus-que-parfait 的时间线意识。',grammar:['passé composé：完成事件、结果','imparfait：背景、状态、习惯','plus-que-parfait：过去参照点之前已发生'],example:'La réforme a provoqué des réactions. La situation était difficile. Les autorités avaient déjà pris des mesures.',reading:['读2篇社会新闻：先标题/首段，再每段首句','给每篇写主旨、作者目的、三段结构','精读6句：圈出主语、谓语、宾语'],vocab:['prendre des mesures','réduire les inégalités','faire face à un problème','être confronté à une difficulté','mettre en place un dispositif'],task:[['语法训练','20题','区分三种过去时'],['阅读训练','2篇','每篇限时12分钟'],['词块记忆','15个','名词+动词搭配']],quiz:[['哪一项通常表示背景？',['passé composé','imparfait','plus-que-parfait'],1],['“此前已经采取”应使用？',['a pris','prenait','avait pris'],2],['TCF阅读第一步应做什么？',['逐词翻译','先确定主旨','先查所有生词'],1]]},
 {n:2,title:'过去时的语义差别',tag:'时间线 · 社会问题',goal:'在报道中区分背景、主事件、先前原因和结果。',grammar:['事件与状态的对比','过去时构成的时间线','因果关系中的先后'],example:'La réforme a provoqué des réactions. Les citoyens étaient mécontents. Le gouvernement avait sous-estimé le problème.',reading:['读历史/社会报道与评论各1篇','标记所有过去时并画时间线','精读4个含两个从句的长句'],vocab:['aggraver une situation','compenser les inégalités','exclure une partie de la population','bénéficier d’un soutien','se traduire par'],task:[['语法训练','25题','画出事件顺序'],['阅读训练','2篇','找背景与主事件'],['复盘','15分钟','记录时态误判']],quiz:[['“背景状态”最常用？',['imparfait','passé simple','futur antérieur'],0],['更早发生的事件用？',['présent','plus-que-parfait','conditionnel'],1],['选项把假设说成事实时应？',['选择它','排除它','忽略题干'],1]]},
 {n:3,title:'未来、预测与不确定性',tag:'futur antérieur · 科技',goal:'识别将来完成、预测和媒体中的谨慎表达。',grammar:['futur simple：将来事实/预测','futur antérieur：将来某时之前完成','conditionnel présent：可能、推测、谨慎报道'],example:'D’ici 2030, les émissions auront diminué. Cette mesure pourrait réduire les coûts.',reading:['读科技预测和经济预测各1篇','把句子分为事实、预测、推测','分析6句时间从句'],vocab:['stimuler l’innovation','accélérer la transition','transformer les pratiques','anticiper les risques','être susceptible de modifier'],task:[['语法训练','25题','判断语气强度'],['阅读训练','2篇','找预测句'],['词块记忆','18个','用同义词串联']],quiz:[['“到2030年前将已经减少”是？',['futur simple','futur antérieur','imparfait'],1],['pourrait通常表示？',['确定事实','可能/推测','过去习惯'],1],['预测文章先找什么？',['所有生词','时间标记和主旨','作者姓名'],1]]},
 {n:4,title:'条件式与三种假设',tag:'si结构 · 经济',goal:'区分真实条件、现在/将来假设和过去未实现假设。',grammar:['si + présent → futur/présent','si + imparfait → conditionnel présent','si + plus-que-parfait → conditionnel passé'],example:'Si des mesures avaient été prises plus tôt, la crise aurait été évitée.',reading:['读政策评论和调查报道各1篇','标记5个 si 结构','排除把假设说成已发生的选项'],vocab:['créer des emplois','réduire le chômage','relancer l’économie','connaître une croissance','être soumis à une pression'],task:[['语法训练','30题','三种假设互换'],['阅读训练','2篇','判断事实/假设'],['词块记忆','18个','经济问题—措施']],quiz:[['si + imparfait对应？',['现在/将来假设','过去完成事实','确定结果'],0],['过去未实现结果用？',['futur simple','conditionnel passé','imparfait'],1],['si从句阅读重点是？',['条件与结果关系','冠词','发音'],0]]},
 {n:5,title:'虚拟式：让步与目的',tag:'subjonctif · 教育健康',goal:'识别必要性、让步、目的和不确定性。',grammar:['il faut que','bien que / quoique','pour que / afin que / avant que'],example:'Bien que la situation soit complexe, une solution existe. Il faut que les autorités prennent des mesures.',reading:['读教育政策和健康文章各1篇','圈出让步、目的、必要性触发词','精读6个虚拟式从句'],vocab:['améliorer l’accès aux soins','prévenir une maladie','réduire les risques','favoriser la réussite scolaire','garantir l’égalité des chances'],task:[['语法训练','30题','找触发结构'],['阅读训练','2篇','主句/让步句'],['词块记忆','18个','健康与教育']],quiz:[['bien que表达？',['原因','让步','结果'],1],['“为了让每个人受益”用？',['afin que','malgré','puisque'],0],['虚拟式本身主要说明？',['结构触发的语气','时间必然过去','复数'],0]]},
 {n:6,title:'关系代词拆长句',tag:'qui · que · dont · 环境',goal:'找先行词，删除修饰后先读主干。',grammar:['qui：从句主语','que：从句宾语','dont：de + 名词/动词','lequel系列：正式介词结构'],example:'Le problème dont il est question reste difficile à résoudre.',reading:['读环境调查和科学说明各1篇','括出关系从句，删除后找主干','分析8句并标出先行词'],vocab:['lutter contre le réchauffement climatique','réduire les émissions','préserver la biodiversité','protéger les ressources','être responsable de'],task:[['语法训练','30题','关系代词填空'],['阅读训练','2篇','主干/修饰分层'],['精读','8句','写先行词']],quiz:[['qui后面通常直接接？',['动词','冠词','介词'],0],['dont常等于？',['à + 名词','de + 名词/动词','pour + 动词'],1],['长句第一步？',['找主干','查词典','翻译每个词'],0]]},
 {n:7,title:'复合关系代词与指代',tag:'auquel · ce qui · 人工智能',goal:'处理正式文章中的复杂指代和整个事实的概括。',grammar:['auquel / auxquels','duquel / desquels','ce qui / ce que / ce dont'],example:'Ce que montre cette étude, c’est l’importance du contexte.',reading:['读人工智能专题2篇','标出指代对象','精读8句并判断 ce 指代什么'],vocab:['déployer une technologie','collecter des données','protéger les données personnelles','automatiser une tâche','soulever des questions éthiques','encadrer l’usage de'],task:[['语法训练','30题','复合代词选择'],['阅读训练','2篇','指代定位'],['词块记忆','20个','科技伦理']],quiz:[['ce qui后通常接？',['动词','限定词+名词','介词'],0],['auquel由什么合成？',['à + lequel','de + lequel','pour + lequel'],0],['指代题先确认？',['ce的对象','文章字数','标题长度'],0]]},
 {n:8,title:'被动与无人称表达',tag:'正式文体 · 公共政策',goal:'适应政府公告和机构报告的客观表达。',grammar:['被动：être + participe passé','il convient de / il s’agit de','il semblerait que / il ressort que'],example:'La décision a été critiquée. Il convient de prendre en compte les conséquences sociales.',reading:['读公告和机构报告各1篇','分析6个无人称结构','做主动/被动互换'],vocab:['adopter une loi','mettre en œuvre une politique','évaluer un dispositif','financer un projet','répondre à un enjeu','produire des effets'],task:[['语法训练','25题','主动被动转换'],['阅读训练','2篇','判断形式主语'],['词块记忆','18个','政策动作']],quiz:[['被动语态强调？',['动作接受者','说话人身份','时间地点'],0],['il convient de表示？',['适合/应当','过去已经','虽然'],0],['il s’agit de后面常接？',['名词或不定式','过去分词','比较级'],0]]},
 {n:9,title:'名词化与信息压缩',tag:'报告文体 · 全球化',goal:'把名词化还原为动作，确认主语和因果。',grammar:['la mise en place de','la réduction / augmentation de','la remise en cause de'],example:'La réduction des dépenses a suscité des critiques.',reading:['读经济分析和社会评论各1篇','将8句名词化改写为简单句','检查选项是否偷换动作主体'],vocab:['stimuler la croissance','attirer les investissements','accroître la compétitivité','renforcer les échanges','dépendre de facteurs extérieurs','remettre en cause un modèle'],task:[['语法训练','25题','名词化还原'],['阅读训练','2篇','找压缩信息'],['词块记忆','20个','经济因果']],quiz:[['名词化的作用通常是？',['压缩信息','改变时态','表示疑问'],0],['“投资增加”可名词化为？',['l’augmentation des investissements','les investissements augmentaient','augmenterait'],0],['还原时先找？',['动作和主语','所有同义词','作者国籍'],0]]},
 {n:10,title:'逻辑连接词地图',tag:'因果让步 · 文化媒体',goal:'给每段贴逻辑标签，快速判断论证方向。',grammar:['原因：puisque / étant donné que','让步：cependant / bien que / malgré','结果：ainsi / donc / de sorte que','目的：afin de / en vue de'],example:'Les résultats sont positifs, bien que les effets restent limités.',reading:['读评论文章2篇','每段标原因、转折、例证或结论','精读8句，圈连接词'],vocab:['diffuser une information','accéder à la culture','préserver le patrimoine','véhiculer une image','susciter un débat','mettre en lumière'],task:[['语法训练','30题','连接词分类'],['阅读训练','2篇','段落逻辑标签'],['词块记忆','18个','媒体表达']],quiz:[['cependant表达？',['转折','原因','目的'],0],['étant donné que表达？',['原因','结果','时间'],0],['转折词后通常？',['重点或修正观点','无关信息','标题'],0]]},
 {n:11,title:'passé simple阅读识别',tag:'历史叙事 · 文化',goal:'识别正式叙事中的完成事件，不要求主动使用。',grammar:['il fut / il eut / il fit','il prit / il vint / il put','ils firent / ils décidèrent'],example:'La réforme fut adoptée en 1995. Les chercheurs découvrirent une nouvelle méthode.',reading:['读历史文化文章2篇','把 passé simple 换成 passé composé','精读6句并画事件线'],vocab:['marquer un tournant','jouer un rôle majeur','laisser une trace','s’inscrire dans une tradition','être considéré comme','faire l’objet de'],task:[['语法训练','25题','形式识别'],['阅读训练','2篇','叙事顺序'],['词块记忆','15个','文化史表达']],quiz:[['passé simple主要需要？',['阅读识别','主动造句','口语练习'],0],['fut相当于现代的？',['a été','était','sera'],0],['历史叙事先抓？',['事件顺序','每个冠词','发音'],0]]},
 {n:12,title:'长句主干工作坊',tag:'插入语 · 就业',goal:'处理信息嵌套，稳定找到主语和有限动词。',grammar:['插入语与同位语','现在/过去分词短语','关系从句嵌套'],example:'Cette mesure, annoncée au début de l’année, devrait entrer en vigueur prochainement.',reading:['读科技或经济长文2篇','每篇拆解8句','写“主语—谓语—宾语—修饰”'],vocab:['évoluer sur le marché du travail','acquérir des compétences','rester compétitif','améliorer les conditions de travail','concilier vie professionnelle et vie privée','faire face à une pénurie'],task:[['语法训练','25题','括号标插入语'],['阅读训练','2篇','8句主干拆解'],['词块记忆','18个','就业搭配']],quiz:[['长句第一动作？',['找有限动词','先查生词','看句号数量'],0],['插入语通常？',['可暂时删除读主干','决定所有时态','总是主句'],0],['souhaitant réduire是？',['分词短语','被动语态','虚拟式'],0]]},
 {n:13,title:'因果、目的、让步和结果',tag:'逻辑链 · 健康环境',goal:'准确画出“原因→措施→结果”，不倒置方向。',grammar:['parce que / puisque / comme','bien que / quoique','pour que / afin que','de sorte que / sans que'],example:'La mesure a été renforcée de sorte que les usagers puissent être mieux protégés.',reading:['读健康与环境文章各1篇','画原因→措施→结果链','精读8句逻辑从句'],vocab:['avoir des conséquences sur','entraîner une hausse','contribuer à réduire','prévenir les risques','prendre en charge','être exposé à','dépendre de'],task:[['语法训练','30题','逻辑方向'],['阅读训练','2篇','原因结果链'],['词块记忆','20个','问题与措施']],quiz:[['de sorte que表达？',['结果','让步','原因'],0],['bien que后通常？',['让步背景','确定结果','时间点'],0],['因果题最怕？',['原因结果倒置','识别标题','看连接词'],0]]},
 {n:14,title:'陌生主题生存法',tag:'跨主题 · 综合',goal:'遇到社会、科技、经济混合文章时依靠结构和词块理解。',grammar:['综合复习时态','综合复习条件式/虚拟式','综合复习关系代词与被动'],example:'Il est probable que cette évolution entraîne de nouvelles inégalités.',reading:['读社会、科技、经济3篇','每篇5分钟判断文体和主旨','任选一篇精读10句'],vocab:['soulever un enjeu','identifier les causes','mettre en œuvre une solution','évaluer les résultats','tirer les conséquences','adopter une approche'],task:[['语法训练','40题','综合辨认'],['阅读训练','3篇','陌生主题'],['词块记忆','25个','问题—措施—结果']],quiz:[['陌生主题先看？',['结构和主旨','所有生词','参考答案'],0],['enjeu最接近？',['重要问题/挑战','天气','人物'],0],['作者文体判断有助于？',['预判信息组织','背变位','发音'],0]]},
 {n:15,title:'第一次完整模拟',tag:'限时 · 诊断',goal:'完成一套完整阅读模拟，找到最大失分点。',grammar:['复习错误率最高的3类','对比 bien que / même si / malgré','整理个人错题标签'],example:'每道错题归类：词汇、句法、逻辑、定位、选项陷阱或时间不足。',reading:['完整TCF阅读模拟1套，严格限时','精读错题句10句','统计每题耗时和题型'],vocab:['复习Day 1—14全部词块','新增10个正式表达','只保留真正影响理解的生词'],task:[['模拟阅读','1套','严格计时'],['错题复盘','40分钟','写清为什么错'],['词块复习','50个','双向回忆']],quiz:[['模拟后第一步？',['分类错因','马上背新词','重做全部文章'],0],['过度绝对的选项通常？',['需要警惕','一定正确','优先选择'],0],['错题句精读目的？',['修复方法','装饰笔记','练发音'],0]]},
 {n:16,title:'针对性修复',tag:'薄弱项 · 定向',goal:'根据模拟结果只攻一个主弱项，避免分散学习。',grammar:['时态错多：过去时/条件式','结构错多：关系代词/从句','逻辑错多：连接词','细节错多：被动/无人称/名词化'],example:'先把复杂句改成简单句，再恢复复杂句，检查信息是否丢失。',reading:['选择个人薄弱主题2篇','分析10句：主句、从句、逻辑、关键词','每篇最多查8个词'],vocab:['薄弱主题20个词块','用同义替换成组记忆','将词块放入问题—措施—结果'],task:[['语法训练','35题','只攻主弱项'],['阅读训练','2篇','10句结构分析'],['错题回做','20题','隔天验证']],quiz:[['修复日应该？',['集中一个弱项','四处学新语法','跳过错题'],0],['生词最多查多少个/篇？',['8个','全部','0个'],0],['复杂句先做什么？',['改成简单句','背下来','删除'],0]]},
 {n:17,title:'选项排除与生词处理',tag:'考试技巧 · 新闻',goal:'提高定位速度，处理不会的词而不被拖住。',grammar:['depuis / pendant / il y a','avant que / avant de','ce qui / ce que / dont','si三种假设'],example:'排除四步：定位原文 → 检查主语 → 检查时间和程度 → 检查是否加入新信息。',reading:['3篇中等长度文章','每篇限时完成并写排除理由','生词先判断是否影响主旨'],vocab:['selon les données disponibles','d’après plusieurs études','à l’heure actuelle','dans un contexte marqué par','il ressort que','les chiffres montrent que'],task:[['语法训练','30题','易混结构'],['阅读训练','3篇','排除法'],['词块记忆','20个','新闻正式表达']],quiz:[['选项先检查？',['主语是否一致','字数','标点'],0],['不影响主旨的生词？',['先跳过','立刻查','停止做题'],0],['比原文更绝对的选项？',['警惕','优先','必对'],0]]},
 {n:18,title:'第二次完整模拟',tag:'限时 · 稳定',goal:'检验速度和稳定性，比较两次模拟的错误类型。',grammar:['只复习错题本','看到结构立即判断功能','不再学习大块新语法'],example:'记录每题平均时间、最弱题型、最弱主题和生词造成的实际失分。',reading:['完整TCF阅读模拟1套','精读错题8句','与Day15对比正确率和用时'],vocab:['复习全部主题词块','新增10个逻辑表达','把不必要的生词移出清单'],task:[['模拟阅读','1套','严格计时'],['错题复盘','45分钟','与第一次对比'],['词块复习','60个','快速回忆']],quiz:[['第二次模拟要比较？',['正确率和时间','字体大小','文章页数'],0],['最后阶段应避免？',['大块新语法','复习错题','限时训练'],0],['错题复盘要看？',['错误类型','答案字母','文章长度'],0]]},
 {n:19,title:'知识压缩与快速调用',tag:'100点清单 · 反应',goal:'让高频结构在考场中自动触发，而不是继续扩张内容。',grammar:['过去时四分法','futur antérieur / 条件式','虚拟式触发词','关系代词/被动/名词化/连接词'],example:'每类语法只做5题，重点是看到结构后立即说出功能。',reading:['2篇限时阅读+1篇精读','每篇写一句主旨和作者态度','标出3个连接词、2个词块'],vocab:['复习100个核心词块','法语→中文、中文→法语双向回忆','把同义词成组'],task:[['语法训练','40题','快速反应'],['阅读训练','3篇','主旨/态度'],['词块复习','100个','双向回忆']],quiz:[['Day19的重点？',['调用速度','增加新量','全文翻译'],0],['每篇阅读应总结？',['主旨和态度','作者生日','词数'],0],['核心词块最好？',['双向回忆','只看中文','只抄写'],0]]},
 {n:20,title:'轻量收官与考试节奏',tag:'复习 · 稳定',goal:'保持状态，不再引入新内容，用稳定节奏进入考试。',grammar:['复习错题本','复习100个语法/表达点','回顾最容易混淆的10组结构'],example:'今天不追求全部理解：先主旨，后定位，再检查时间、主语、程度和因果。',reading:['半套或一套轻量模拟','只分析错题，不学大量新材料','覆盖主旨、态度、推断、细节四类题'],vocab:['复习150个高频词块','不背新词','晚上停止高强度学习并保证睡眠'],task:[['语法训练','20—25题','只复习'],['阅读训练','半套/1套','保持节奏'],['词块复习','150个','快速回忆']],quiz:[['考前最后一天应该？',['巩固不扩张','通宵背词','学习新语法'],0],['文章信息顺序？',['主旨→定位→核对','逐词翻译','先查词'],0],['最重要的恢复措施？',['睡眠','继续加量','跳过复盘'],0]]}
];

const storeKey='tcf-b2-progress-v1';
let progress=JSON.parse(localStorage.getItem(storeKey)||'{}');
let selected=Number(localStorage.getItem('tcf-b2-selected')||1);
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(storeKey,JSON.stringify(progress)); localStorage.setItem('tcf-b2-selected',selected);}
function completedCount(){return days.filter(d=>progress[d.n]?.done).length}
function renderProgress(){const count=completedCount(),pct=Math.round(count/days.length*100);$('#dayCount').textContent=`${count}/20`;$('#progressText').textContent=`${count} / 20 天`;$('#progressPct').textContent=`${pct}%`;$('#ring').style.strokeDashoffset=314-(314*pct/100);$('#continueBtn').innerHTML=count<20?`继续第 ${Math.min(count+1,20)} 天 <span>→</span>`:'查看第20天复盘 <span>→</span>';}
function renderDays(){const list=$('#dayList');list.innerHTML=days.map(d=>`<button class="day-item ${d.n===selected?'active ':''}${progress[d.n]?.done?'done':''}" data-day="${d.n}" type="button"><span class="day-num">${String(d.n).padStart(2,'0')}</span><span><b>Day ${d.n}</b><small>${d.tag}</small></span><span class="check">✓</span></button>`).join('');list.querySelectorAll('.day-item').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.day);save();render();$('#lessonPanel').scrollIntoView({behavior:'smooth',block:'start'})}));}
function renderLesson(){const d=days.find(x=>x.n===selected),done=!!progress[d.n]?.done;$('#lessonPanel').innerHTML=`<div class="lesson-head"><div><p class="lesson-kicker">DAY ${String(d.n).padStart(2,'0')} · ${d.tag.toUpperCase()}</p><h2>${d.title}</h2><p class="subtitle">${d.goal}</p></div><button class="complete-btn ${done?'completed':''}" id="completeBtn" type="button">${done?'✓ 今日已完成':'标记今天完成'}</button></div><div class="lesson-grid"><article class="lesson-card"><h3><span class="card-icon">文</span>语法学习</h3><ul>${d.grammar.map(x=>`<li>${x}</li>`).join('')}</ul><div class="example">${d.example}<small>阅读识别：先找结构，再判断语义。</small></div></article><article class="lesson-card why"><h3><span class="card-icon">靶</span>今日阅读目标</h3><ul>${d.reading.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="lesson-card"><h3><span class="card-icon">词</span>B2词块</h3><div class="chips">${d.vocab.map(x=>`<span>${x}</span>`).join('')}</div><p class="muted">记忆法：不要孤立背诵。朗读搭配，写一个和今天主题有关的短句。</p></article><article class="lesson-card"><h3><span class="card-icon">✓</span>今日训练量</h3>${d.task.map(x=>`<div class="task-row"><p>${x[0]}</p><span>${x[1]} · ${x[2]}</span></div>`).join('')}</article><article class="lesson-card quiz wide"><h3><span class="card-icon">?</span>3分钟自测</h3><p class="quiz-intro">每题只有一个最佳答案。完成后查看得分；错题请回到上面的例句重新分析。</p>${d.quiz.map((q,i)=>`<div class="question" data-q="${i}"><p>${i+1}. ${q[0]}</p><div class="options">${q[1].map((o,j)=>`<button class="option" data-answer="${j}" type="button">${o}</button>`).join('')}</div></div>`).join('')}<div class="quiz-result" id="quizResult"></div></article></div>`;$('#completeBtn').addEventListener('click',()=>{progress[d.n]={...(progress[d.n]||{}),done:!done};save();render()});document.querySelectorAll('.option').forEach(btn=>btn.addEventListener('click',()=>answer(btn,d)));}
function answer(btn,d){const qEl=btn.closest('.question');if(qEl.dataset.answered)return;const qi=Number(qEl.dataset.q),correct=d.quiz[qi][2],chosen=Number(btn.dataset.answer);qEl.dataset.answered='1';qEl.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(i===correct)b.classList.add('correct')});if(chosen!==correct)btn.classList.add('wrong');const done=[...document.querySelectorAll('.question[data-answered]')].length;const score=[...document.querySelectorAll('.question')].reduce((n,e,i)=>n+(e.querySelector('.option.correct')?.classList.contains('wrong')?0:([...e.querySelectorAll('.option')].findIndex(x=>x.classList.contains('wrong'))<0&&e.querySelector('.option.correct')?.disabled?1:0)),0);$('#quizResult').textContent=done===3?`本次完成：${score} / 3。${score===3?'结构掌握得很好，继续完成今天的训练。':'把错题重新读一遍，再做一次同类题。'}`:`已完成 ${done} / 3 题`}
function render(){renderProgress();renderDays();renderLesson()}
$('#continueBtn').addEventListener('click',()=>{selected=Math.min(completedCount()+1,20);save();render();$('#course').scrollIntoView({behavior:'smooth'})});$('#overviewBtn').addEventListener('click',()=>$('#course').scrollIntoView({behavior:'smooth'}));$('#resetBtn').addEventListener('click',()=>{if(confirm('确定清除本设备上的学习进度吗？')){progress={};selected=1;save();render()}});render();

const resourceData={
 overview:{title:'为什么20天值得这样练',html:`<div class="resource-grid"><div class="resource-box"><h4>B1 → B2 最大差距</h4><ul><li>B2文章信息密度更高，多个观点、原因、结果和例外常压缩在长句里。</li><li>正确选项常是改写或概括，需要区分事实、观点和推论。</li><li>正式主题词汇更抽象：社会、环境、科技、经济、文化和公共政策。</li></ul></div><div class="resource-box"><h4>最高收益投入</h4><ul><li>过去时、条件式、虚拟式和关系代词。</li><li>长句主干、逻辑连接词和TCF限时题型。</li><li>名词+动词词块，而不是孤立单词。</li></ul></div></div><h4>可以暂时放弃</h4><p>写作、口语、发音、低频文学词汇、过于专业的术语、完整掌握所有变位、全文逐词翻译，以及 <code>passé simple</code> 的主动使用。</p><h4>每道错题都这样复盘</h4><p>给错题贴一个标签：词汇、句法、逻辑、定位、选项陷阱或时间管理。然后写一句“下次看到什么信号就能避免”。</p>`},
 template:{title:'每天3小时固定模板',html:`<div class="resource-grid"><div class="resource-box"><h4>标准日 · 180分钟</h4><ul><li><b>40分钟语法：</b>15分钟规则，20分钟做题，5分钟整理错因。</li><li><b>60分钟阅读：</b>10分钟浏览，35分钟做题，15分钟分析定位和选项。</li><li><b>40分钟词汇：</b>20分钟新词块，10分钟旧词块，10分钟搭配和同义替换。</li><li><b>40分钟复盘：</b>长句分析、错题重做、记录为什么错。</li></ul></div><div class="resource-box"><h4>模拟日 · 180分钟</h4><ul><li>90分钟完整阅读模拟。</li><li>40分钟语法错题。</li><li>30分钟词块复习。</li><li>20分钟错题分类。</li></ul></div></div><h4>阅读三层法</h4><p><b>第一层：</b>快速确定主旨、作者观点和文章结构。<br><b>第二层：</b>找主干、判断从句关系、圈逻辑连接词。<br><b>第三层：</b>定位原文，检查选项的主语、时间、程度、因果关系；生词先判断是否影响主旨。</p>`},
 sprint:{title:'最后5天冲刺安排',html:`<div class="resource-grid"><div class="resource-box"><h4>Day 16 · 修复</h4><p>根据第一次模拟只攻一个最大弱项。复杂句先改成简单句，再恢复原结构。</p></div><div class="resource-box"><h4>Day 17 · 排除</h4><p>练习定位、主语/时间/程度核对，以及不影响主旨的生词跳过法。</p></div><div class="resource-box"><h4>Day 18 · 模拟</h4><p>完成第二套完整阅读模拟，比较正确率、平均用时和错误类型。</p></div><div class="resource-box"><h4>Day 19 · 压缩</h4><p>复习高频语法和100个词块，每类语法只做5题，练结构反应。</p></div><div class="resource-box"><h4>Day 20 · 收官</h4><p>做半套或轻量模拟，不学新内容，早点停止高强度学习并保证睡眠。</p></div></div><h4>考场排除四步</h4><p>① 找原文定位句；② 检查主语是否一致；③ 检查时间、程度和因果；④ 排除加入原文没有信息或表达过度绝对的选项。</p>`},
 points:{title:'TCF B2阅读100个核心语法/表达点',html:''}
};
resourceData.points.html='<ol class="point-list">'+['passé composé','imparfait','plus-que-parfait','passé simple','futur simple','futur antérieur','conditionnel présent','conditionnel passé','subjonctif présent','过去时的时间先后','背景与主事件','完成事件与持续状态','过去未实现假设','媒体中的谨慎条件式','将来完成动作','si + présent','si + imparfait','si + plus-que-parfait','à condition que','à moins que','sous réserve de','dans le cas où','pourvu que','en cas de','faute de','il faut que','il est nécessaire que','bien que','quoique','pour que','afin que','avant que','sans que','à condition que','il est possible que','il est peu probable que','craindre que','douter que','vouloir que','souhaiter que','qui','que','dont','où','lequel','laquelle','lesquels','lesquelles','auquel','auxquels','à laquelle','auxquelles','duquel','desquels','de laquelle','desquelles','ce qui','ce que','ce dont','ce à quoi','被动语态','être censé','être considéré comme','il s’agit de','il convient de','il semble que','il semblerait que','il est question de','il ressort que','il est probable que','无人称 il','名词化','同位语','插入语','分词短语','长定语','过去分词作定语','现在分词作定语','不定式目的结构','en + participe présent','cependant','pourtant','en revanche','toutefois','néanmoins','tandis que','alors que','bien que','malgré','puisque','étant donné que','du fait de','ainsi','donc','de sorte que','par conséquent','afin de','en vue de','dans la mesure où','dès lors'].map((x,i)=>`<li><b>${i+1}.</b> ${x}</li>`).join('')+'</ol>';
function renderResources(kind='overview'){const data=resourceData[kind]||resourceData.overview;$('#resourceContent').innerHTML=`<h3>${data.title}</h3>${data.html}`;document.querySelectorAll('.resource-tab').forEach(b=>b.classList.toggle('active',b.dataset.resource===kind));}
document.querySelectorAll('.resource-tab').forEach(b=>b.addEventListener('click',()=>renderResources(b.dataset.resource)));renderResources();
